"""init_tracks

Revision ID: fe7b962e978d
Revises: cea640e4c1c8
Create Date: 2025-07-26 16:10:27.409724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe7b962e978d"
down_revision: Union[str, None] = "cea640e4c1c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("title", sa.String(), nullable=False, comment="Genre's title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Genre's description",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_genres_uuid"), "genres", ["uuid"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("title", sa.String(), nullable=False, comment="Track's title"),
        sa.Column(
            "duration",
            sa.Integer(),
            nullable=False,
            comment="Track's duration",
        ),
        sa.Column(
            "audio_url",
            sa.String(),
            nullable=True,
            comment="Audio's url in minio",
        ),
        sa.Column("bitrate", sa.String(), nullable=False, comment="Track's bitrate"),
        sa.Column(
            "format",
            sa.Enum("MP3", "FLAC", "AAC", name="trackformat"),
            nullable=False,
            comment="Track's format",
        ),
        sa.Column(
            "artist_uuid",
            sa.UUID(),
            nullable=False,
            comment="Artist's unique id",
        ),
        sa.Column(
            "album_uuid",
            sa.UUID(),
            nullable=False,
            comment="Album's unique id",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["album_uuid"],
            ["albums.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_uuid"],
            ["artists.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        op.f("ix_tracks_album_uuid"), "tracks", ["album_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_tracks_artist_uuid"), "tracks", ["artist_uuid"], unique=False
    )
    op.create_index(op.f("ix_tracks_uuid"), "tracks", ["uuid"], unique=False)
    op.add_column(
        "albums",
        sa.Column(
            "release_date",
            sa.DateTime(),
            nullable=True,
            comment="Release date",
        ),
    )
    op.add_column(
        "albums",
        sa.Column("genre_uuid", sa.UUID(), nullable=True, comment="Artist's genre id"),
    )
    op.create_index(
        op.f("ix_albums_genre_uuid"), "albums", ["genre_uuid"], unique=False
    )
    op.create_foreign_key(None, "albums", "genres", ["genre_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "albums", type_="foreignkey")
    op.drop_index(op.f("ix_albums_genre_uuid"), table_name="albums")
    op.drop_column("albums", "genre_uuid")
    op.drop_column("albums", "release_date")
    op.drop_index(op.f("ix_tracks_uuid"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_artist_uuid"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_album_uuid"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_genres_uuid"), table_name="genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
