"""init_albums

Revision ID: cea640e4c1c8
Revises: de221ba213d3
Create Date: 2025-07-26 15:05:18.192120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea640e4c1c8"
down_revision: Union[str, None] = "de221ba213d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("title", sa.String(), nullable=False, comment="Album's title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Album's description",
        ),
        sa.Column(
            "cover_url",
            sa.String(),
            nullable=True,
            comment="Cover's url in minio",
        ),
        sa.Column(
            "artist_uuid",
            sa.UUID(),
            nullable=False,
            comment="Artist's unique id",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["artist_uuid"],
            ["artists.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        op.f("ix_albums_artist_uuid"), "albums", ["artist_uuid"], unique=False
    )
    op.create_index(op.f("ix_albums_uuid"), "albums", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_albums_uuid"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist_uuid"), table_name="albums")
    op.drop_table("albums")
    # ### end Alembic commands ###
