import typing
import uuid


class UseCaseInterface(typing.Protocol):
    async def get_item(self, uuid: str | uuid.UUID): ...
    async def get_items(self, filters): ...
    async def create_item(self, data): ...
    async def update_item(self, uuid, data): ...
    async def delete_item(self, uuid): ...
